# Generated by Django 6.1.1 on 2026-09-23 15:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_poster_url_alter_movie_status_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchlist_movies', to=settings.AUTH_USER_MODEL),
        ),
    ]
