# Generated by Django 6.1.1 on 2026-09-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='accent_color',
            field=models.CharField(default='#38bdf8', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bg_color',
            field=models.CharField(default='#0f172a', max_length=20),
        ),
    ]
